export const exercisesFakeData = [
  { name: 'Abs', isSelected: true },
  { name: 'Squat', isSelected: false },
  { name: 'Pull up', isSelected: false },
  { name: 'Push up', isSelected: false },
  { name: 'Abs', isSelected: false },
  { name: 'Squat', isSelected: false },
  { name: 'Pull up', isSelected: false },
  { name: 'Push up', isSelected: false },
  { name: 'Abs', isSelected: false },
  { name: 'Squat', isSelected: false },
  { name: 'Pull up', isSelected: false },
  { name: 'Push up', isSelected: false },
  { name: 'Abs', isSelected: false },
  { name: 'Squat', isSelected: false },
  { name: 'Pull up', isSelected: false },
]
